// Generated by CoffeeScript 1.7.1
(function() {
  var initLightbox;

  initLightbox = function() {
    var imgs, wrap;
    wrap = $('#m-col');
    imgs = wrap.find('a > img');
    imgs.each(function() {
      var t;
      t = $(this);
      return t.parent('a').attr('title', t.attr('alt'));
    });
    return imgs.parent('a').magnificPopup({
      type: 'image',
      gallery: {
        enabled: true,
        preload: [0, 2]
      }
    });
  };

  $(function() {
    return initLightbox();
  });

}).call(this);
